### ISSUE TITLE
App crashes when..

### ISSUE THREAD

**Issue by SaifAlDilaimi** [JonathanGurebo/UITextFieldLimit#2]
Unfornately I'm getting the same (BAD_EXE) Error on your component. It's kinda crazy: when I type something in the TextField on the second, max third, character it crashes. But if I type with my keyboard (not over the touchscreen) on my mac it doesn't crash. Also when opening the emoji board (Tested on iPhone 5s and Simulator 4inch 32bit)

**Comment by JonathanGurebo** [comment]
Strange.....I read that BAD_EXE_ACCESS has something with ARC(Automatic Reference Counting) to do. Maybe I did something wrong? Need to do something with the variables? I have no experience about ARC

**Comment by SaifAlDilaimi** [comment]
good point! When I'm back home I gonna review the variables and propertys

**Comment by SaifAlDilaimi** [comment]
So I found out why. Its the delegate = self;

Here are few sources, maybe you unstand how to fix it. I dont:

http://stackoverflow.com/questions/11136345/subclass-of-uitextfield

http://stackoverflow.com/questions/1747777/self-delegate-self-whats-wrong-in-doing-that

**Comment by SaifAlDilaimi** [comment]
Tried to implement it,, but didnt worked out. Maybe you do.. https://github.com/deada92/UITextFieldLimit

**Comment by JonathanGurebo** [comment]
I just did a Delegate, works great, but the app still crashes. I also overwriting the Normal UITextFieldDelegate. See https://github.com/JonathanGurebo/UITextFieldLimit and see https://github.com/JonathanGurebo/UITextFieldLimit/wiki/UITextFieldLimitDelegate-Documentation

**Comment by JonathanGurebo** [comment]
I also overwriting the Normal UITextFieldDelegate, what I mean by that is that the user can't subscribe to the normal UITextFieldDelegate which is not good.

**Comment by JonathanGurebo** [comment]
I think it's a bug, or a loop thats going around somewhere.

**Comment by SaifAlDilaimi** [comment]
Sofar as I understood is that Basically, the reason for the "freeze" when you click on your UITextField with itself as a delegate is that respondsToSelector is calling itself -> infinite recursion.

**Comment by JonathanGurebo** [comment]
Yeah, good point. Maybe a subclass should not subscribe to a superclass delegate?

**Comment by SaifAlDilaimi** [comment]
That sucks. There has to be a solution..

**Comment by JonathanGurebo** [comment]
Yeah, we must solve this, ask on StackOverflow? Report to Apple?

But without my Delegate... I have the old files

**Comment by SaifAlDilaimi** [comment]
Hey Jonathan! Sorry I was in vacation for few days. 

Could you ask this already in Stackoverflow? Let me would like to join the conversation!

**Comment by JonathanGurebo** [comment]
Yeah, I will ask. But i'm on a holiday right now. Maybe I will get some time, or maybe we will have to wait.

**Comment by JonathanGurebo** [comment]
Yeah, I will tell you when I have asked the question.

**Comment by JonathanGurebo** [comment]
Sorry for not telling you i'm on a holiday

**Comment by JonathanGurebo** [comment]
But we can work on this project without stress or deadline? :)

**Comment by SaifAlDilaimi** [comment]
Don't worry Jonathan, I got time. I really wonder that nobody had the need to do this before us :D. I kinda think its really important.

I got no deadline, it's just for a app thatt I'm working on.   Anyway I'll try to post a question on SOF as soon a possible. Let see who is first, haha..

**Comment by JonathanGurebo** [comment]
Yeah ok :D

**Comment by JonathanGurebo** [comment]
I fixed the delegate anyway

**Comment by JonathanGurebo** [comment]
I also don't wan't anyone to do this before us :D

**Comment by JonathanGurebo** [comment]
(The project is now under the Apache License 2.0)

I tried to reproduce the bug the simpliest way I could, just implementing the shouldReplaceCharactersInRange:. 

I succeded. I must sleep now, but I'm going to check it out when I got more time. I think it is a bug. If so, I'm going to report it to Apple.
But we will see soon.... :D

**Comment by SaifAlDilaimi** [comment]
Lol Jonathan! Great job! When I get free time I'll try to make its ui costumizable

**Comment by JonathanGurebo** [comment]
I figured it out! it wasen't about the shouldReplaceCharactersInRange:.... It was the overriding method initWithCoder:. I think it is a bug anyway but I solved it. I replaced 'return self;' to 'return [super initWithCoder:decoder];' Uploading soon.....

**Comment by JonathanGurebo** [comment]
Wait... sorry... I was to satisfied. It didn't work in our real class on GitHub, only in my testclass (without the label). But the error is from initWithCoder. Test to delete the method and it will work! But we need to override the method in order to initialize our limitLabel....

**Comment by JonathanGurebo** [comment]
Forget everything.... The problem is just when trying to subscribe to the superclass delegate

**Comment by JonathanGurebo** [comment]
The Bug is confirmed! I received response from Apple. It works perfectly with the latest iOS 8 beta.

**Comment by SaifAlDilaimi** [comment]
Well I wouldnt count on iOS 8, it's really buggy..

**Comment by JonathanGurebo** [comment]
Yeah, but we can wait for a stable release.

**Comment by JonathanGurebo** [comment]
until the fall
